/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/match/auto`; params?: Router.UnknownInputParams; } | { pathname: `/match/conclude`; params?: Router.UnknownInputParams; } | { pathname: `/match`; params?: Router.UnknownInputParams; } | { pathname: `/match/tele`; params?: Router.UnknownInputParams; } | { pathname: `/pit/camera`; params?: Router.UnknownInputParams; } | { pathname: `/pit`; params?: Router.UnknownInputParams; } | { pathname: `/pit/pit-detail-form`; params?: Router.UnknownInputParams; } | { pathname: `/pit/pitdetail`; params?: Router.UnknownInputParams; } | { pathname: `/util/checkbox`; params?: Router.UnknownInputParams; } | { pathname: `/util/counter`; params?: Router.UnknownInputParams; } | { pathname: `/util/match-form`; params?: Router.UnknownInputParams; } | { pathname: `/util/pit-team`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/firebase`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/supabase`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/match/auto`; params?: Router.UnknownOutputParams; } | { pathname: `/match/conclude`; params?: Router.UnknownOutputParams; } | { pathname: `/match`; params?: Router.UnknownOutputParams; } | { pathname: `/match/tele`; params?: Router.UnknownOutputParams; } | { pathname: `/pit/camera`; params?: Router.UnknownOutputParams; } | { pathname: `/pit`; params?: Router.UnknownOutputParams; } | { pathname: `/pit/pit-detail-form`; params?: Router.UnknownOutputParams; } | { pathname: `/pit/pitdetail`; params?: Router.UnknownOutputParams; } | { pathname: `/util/checkbox`; params?: Router.UnknownOutputParams; } | { pathname: `/util/counter`; params?: Router.UnknownOutputParams; } | { pathname: `/util/match-form`; params?: Router.UnknownOutputParams; } | { pathname: `/util/pit-team`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/firebase${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/supabase${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/match/auto${`?${string}` | `#${string}` | ''}` | `/match/conclude${`?${string}` | `#${string}` | ''}` | `/match${`?${string}` | `#${string}` | ''}` | `/match/tele${`?${string}` | `#${string}` | ''}` | `/pit/camera${`?${string}` | `#${string}` | ''}` | `/pit${`?${string}` | `#${string}` | ''}` | `/pit/pit-detail-form${`?${string}` | `#${string}` | ''}` | `/pit/pitdetail${`?${string}` | `#${string}` | ''}` | `/util/checkbox${`?${string}` | `#${string}` | ''}` | `/util/counter${`?${string}` | `#${string}` | ''}` | `/util/match-form${`?${string}` | `#${string}` | ''}` | `/util/pit-team${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/supabase`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/match/auto`; params?: Router.UnknownInputParams; } | { pathname: `/match/conclude`; params?: Router.UnknownInputParams; } | { pathname: `/match`; params?: Router.UnknownInputParams; } | { pathname: `/match/tele`; params?: Router.UnknownInputParams; } | { pathname: `/pit/camera`; params?: Router.UnknownInputParams; } | { pathname: `/pit`; params?: Router.UnknownInputParams; } | { pathname: `/pit/pit-detail-form`; params?: Router.UnknownInputParams; } | { pathname: `/pit/pitdetail`; params?: Router.UnknownInputParams; } | { pathname: `/util/checkbox`; params?: Router.UnknownInputParams; } | { pathname: `/util/counter`; params?: Router.UnknownInputParams; } | { pathname: `/util/match-form`; params?: Router.UnknownInputParams; } | { pathname: `/util/pit-team`; params?: Router.UnknownInputParams; };
    }
  }
}
